esphome:
  name: sample_project
  friendly_name: sample_project

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
logger:
  level: DEBUG
  baud_rate: '115200'

wifi:
  ssid: iot_home_wifi
  password: passwordhere
captive_portal:
debug:
  update_interval: 60s
sensor:
  - platform: dht
    model: DHT22
    pin: '4'
    temperature:
      name: frt Temp
    humidity:
      name: frt Hum
    update_interval: 120s
