esphome:
  name: cucinatemp
  friendly_name: cucinatemp

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
wifi:
  ssid: juri-ufficio-2.4
  password: juri85manuela77
captive_portal:
sensor:
  - platform: dht
    model: DHT11
    pin: '21'
    temperature:
      name: temp_um_cucina_temp
    humidity:
      name: temp_um_cucina_hum
    update_interval: 60s
