ESPHomeGUIeasy: action_block_item.ActionBlockItem Class Reference
action_block_item.ActionBlockItem Class Reference
Public Member Functions
__init__ (self, title="Azione")
setup_ui (self)
toggle_expand (self)
build_from_params (self, param_list)
boundingRect (self)
paint (self, painter, option, widget=None)
remove_from_scene (self)
Public Attributes
width = conf.BLOCK_WIDTH
height = conf.BLOCK_HEIGHT
title = title
bool expanded = True
dict param_widgets = {}
title_item = QGraphicsTextItem(self.title, self)
close_btn = QPushButton()
remove_from_scene
close_proxy = QGraphicsProxyWidget(self)
toggle_btn = QPushButton()
toggle_expand
toggle_proxy = QGraphicsProxyWidget(self)
container = QWidget()
proxy = QGraphicsProxyWidget(self)
Detailed Description
@brief Represents a draggable and expandable action block item in the QGraphicsScene.
Manages UI elements like title label, toggle and close buttons, and dynamic parameter widgets.
Definition at line 29 of file action_block_item.py.
Constructor & Destructor Documentation
__init__()
action_block_item.ActionBlockItem.__init__ (self, title = "Azione")
Definition at line 35 of file action_block_item.py.
    def __init__(self, title="Azione"):
        super().__init__()
        self.width = conf.BLOCK_WIDTH
        self.height = conf.BLOCK_HEIGHT
        self.title = title
        self.expanded = True
        self.param_widgets = {}
        self.setFlags(
            QGraphicsItem.GraphicsItemFlag.ItemIsMovable |
            QGraphicsItem.GraphicsItemFlag.ItemIsSelectable
        )
        self.setup_ui()
References __init__().
Referenced by __init__().
Member Function Documentation
boundingRect()
action_block_item.ActionBlockItem.boundingRect (self)
@brief Returns the bounding rectangle for the block, considering expansion state.
Definition at line 160 of file action_block_item.py.
    def boundingRect(self):
        """
        @brief Returns the bounding rectangle for the block, considering expansion state.
        """
        return QRectF(0, 0, self.width, self.height if self.expanded else conf.BLOCK_COLLAPSED_HEIGHT)
References expanded, height, and width.
Referenced by paint(), condition_block_item.ConditionBlockItem.paint(), script_block_item.ScriptBlockItem.paint(), sensor_block_item.SensorBlockItem.paint(), timer_block_item.TimerBlockItem.paint(), and trigger_block_item.TriggerBlockItem.paint().
build_from_params()
action_block_item.ActionBlockItem.build_from_params (self, param_list)
@brief Builds the UI parameter fields dynamically from a list of parameter definitions.
@param param_list List of dicts defining keys, types, labels, defaults, and options.
Definition at line 122 of file action_block_item.py.
    def build_from_params(self, param_list):
        """
        @brief Builds the UI parameter fields dynamically from a list of parameter definitions.
        @param param_list List of dicts defining keys, types, labels, defaults, and options.
        """
        layout = self.container.layout()
        for param in param_list:
            key = param.get("key")
            tipo = param.get("type")
            label_text = param.get("label", key)
            default = param.get("default", "")
            label = QLabel(label_text)
            layout.addWidget(label)
            if tipo == "text":
                field = QLineEdit()
                field.setPlaceholderText(param.get("placeholder", ""))
                field.setText(str(default))
            elif tipo == "int":
                field = QSpinBox()
                field.setMinimum(0)
                field.setMaximum(100000)
                if isinstance(default, int):
                    field.setValue(default)
            elif tipo == "combo":
                field = QComboBox()
                options = param.get("options", [])
                field.addItems(options)
                if default in options:
                    field.setCurrentText(default)
            else:
                continue
            layout.addWidget(field)
            self.param_widgets[key] = field
References container, and param_widgets.
paint()
action_block_item.ActionBlockItem.paint (self, painter, option, widget = None)
@brief Paints the block rectangle with background color and border.
Definition at line 166 of file action_block_item.py.
    def paint(self, painter, option, widget=None):
        """
        @brief Paints the block rectangle with background color and border.
        """
        painter.setBrush(QBrush(QColor("#e6c229")))  # Giallo
        painter.setPen(QPen(Qt.GlobalColor.black, 2))
        height = int(self.boundingRect().height())
        painter.drawRoundedRect(0, 0, self.width, height, 10, 10)
References boundingRect(), height, and width.
remove_from_scene()
action_block_item.ActionBlockItem.remove_from_scene (self)
@brief Removes this block item from the QGraphicsScene.
Definition at line 175 of file action_block_item.py.
    def remove_from_scene(self):
        """
        @brief Removes this block item from the QGraphicsScene.
        """
        scene = self.scene()
        if scene:
            scene.removeItem(self)
setup_ui()
action_block_item.ActionBlockItem.setup_ui (self)
@brief Sets up the user interface components of the action block, including buttons and container widget.
Definition at line 50 of file action_block_item.py.
    def setup_ui(self):
        """
        @brief Sets up the user interface components of the action block, including buttons and container widget.
        """
        self.title_item = QGraphicsTextItem(self.title, self)
        font = QFont("Consolas", 12, QFont.Weight.Bold)
        self.title_item.setFont(font)
        self.title_item.setDefaultTextColor(Qt.GlobalColor.white)
        self.title_item.setPos(10, 7)
        self.close_btn = QPushButton()
        self.close_btn.setIcon(QIcon(os.path.join(conf.ICON_PATH, "close.png")))
        self.close_btn.setIconSize(QSize(22, 22))
        self.close_btn.setFixedSize(25, 25)
        self.close_btn.setStyleSheet("""
            QPushButton {
                background-color: #ff5f56;
                border: none;
                border-radius: 10px;
            }
            QPushButton:hover {
                background-color: #ff2d20;
            }
        """)
        self.close_btn.clicked.connect(self.remove_from_scene)
        self.close_proxy = QGraphicsProxyWidget(self)
        self.close_proxy.setWidget(self.close_btn)
        self.close_proxy.setPos(self.width - 35, 8)
        self.toggle_btn = QPushButton()
        self.toggle_btn.setIcon(QIcon(os.path.join(conf.ICON_PATH, "expand.png")))
        self.toggle_btn.setIconSize(QSize(22, 22))
        self.toggle_btn.setFixedSize(25, 25)
        self.toggle_btn.setStyleSheet("""
            QPushButton {
                background-color: #e6c229;
                border: none;
                border-radius: 11px;
            }
            QPushButton:hover {
                background-color: #cfa512;
            }
        """)
        self.toggle_btn.clicked.connect(self.toggle_expand)
        self.toggle_proxy = QGraphicsProxyWidget(self)
        self.toggle_proxy.setWidget(self.toggle_btn)
        self.toggle_proxy.setPos(self.width - 74, 8)
        self.container = QWidget()
        layout = QVBoxLayout()
        layout.setContentsMargins(8, 40, 8, 8)
        self.container.setLayout(layout)
        self.container.setFixedWidth(self.width)
        self.proxy = QGraphicsProxyWidget(self)
        self.proxy.setWidget(self.container)
        self.proxy.setPos(0, 40)
toggle_expand()
action_block_item.ActionBlockItem.toggle_expand (self)
@brief Toggles between expanded and collapsed states, showing or hiding the parameters container.
Definition at line 110 of file action_block_item.py.
    def toggle_expand(self):
        """
        @brief Toggles between expanded and collapsed states, showing or hiding the parameters container.
        """
        self.expanded = not self.expanded
        self.container.setVisible(self.expanded)
        self.toggle_btn.setIcon(QIcon(os.path.join(conf.ICON_PATH, "expand.png")))
        self.prepareGeometryChange()
        self.update()
        if self.scene():
            self.scene().update()
References container, expanded, and toggle_btn.
Member Data Documentation
close_btn
action_block_item.ActionBlockItem.close_btn = QPushButton()
Definition at line 60 of file action_block_item.py.
close_proxy
action_block_item.ActionBlockItem.close_proxy = QGraphicsProxyWidget(self)
Definition at line 76 of file action_block_item.py.
container
action_block_item.ActionBlockItem.container = QWidget()
Definition at line 100 of file action_block_item.py.
Referenced by sensor_block_item.SensorBlockItem.aggiorna_label(), sensor_block_item.SensorBlockItem.boundingRect(), build_from_params(), condition_block_item.ConditionBlockItem.build_from_params(), script_block_item.ScriptBlockItem.build_from_params(), timer_block_item.TimerBlockItem.build_from_params(), trigger_block_item.TriggerBlockItem.build_from_params(), sensor_block_item.SensorBlockItem.build_from_returns(), toggle_expand(), condition_block_item.ConditionBlockItem.toggle_expand(), script_block_item.ScriptBlockItem.toggle_expand(), sensor_block_item.SensorBlockItem.toggle_expand(), timer_block_item.TimerBlockItem.toggle_expand(), and trigger_block_item.TriggerBlockItem.toggle_expand().
expanded
action_block_item.ActionBlockItem.expanded = True
Definition at line 40 of file action_block_item.py.
Referenced by boundingRect(), condition_block_item.ConditionBlockItem.boundingRect(), script_block_item.ScriptBlockItem.boundingRect(), sensor_block_item.SensorBlockItem.boundingRect(), timer_block_item.TimerBlockItem.boundingRect(), trigger_block_item.TriggerBlockItem.boundingRect(), toggle_expand(), condition_block_item.ConditionBlockItem.toggle_expand(), script_block_item.ScriptBlockItem.toggle_expand(), sensor_block_item.SensorBlockItem.toggle_expand(), timer_block_item.TimerBlockItem.toggle_expand(), and trigger_block_item.TriggerBlockItem.toggle_expand().
height
action_block_item.ActionBlockItem.height = conf.BLOCK_HEIGHT
Definition at line 38 of file action_block_item.py.
Referenced by boundingRect(), condition_block_item.ConditionBlockItem.boundingRect(), script_block_item.ScriptBlockItem.boundingRect(), timer_block_item.TimerBlockItem.boundingRect(), trigger_block_item.TriggerBlockItem.boundingRect(), and paint().
param_widgets
dict action_block_item.ActionBlockItem.param_widgets = {}
Definition at line 41 of file action_block_item.py.
Referenced by build_from_params(), condition_block_item.ConditionBlockItem.build_from_params(), script_block_item.ScriptBlockItem.build_from_params(), timer_block_item.TimerBlockItem.build_from_params(), trigger_block_item.TriggerBlockItem.build_from_params(), and sensor_block_item.SensorBlockItem.has_valid_data().
proxy
action_block_item.ActionBlockItem.proxy = QGraphicsProxyWidget(self)
Definition at line 106 of file action_block_item.py.
remove_from_scene
action_block_item.ActionBlockItem.remove_from_scene
Definition at line 74 of file action_block_item.py.
title
action_block_item.ActionBlockItem.title = title
Definition at line 39 of file action_block_item.py.
title_item
action_block_item.ActionBlockItem.title_item = QGraphicsTextItem(self.title, self)
Definition at line 54 of file action_block_item.py.
Referenced by sensor_block_item.SensorBlockItem.update_title().
toggle_btn
action_block_item.ActionBlockItem.toggle_btn = QPushButton()
Definition at line 80 of file action_block_item.py.
Referenced by toggle_expand(), condition_block_item.ConditionBlockItem.toggle_expand(), script_block_item.ScriptBlockItem.toggle_expand(), sensor_block_item.SensorBlockItem.toggle_expand(), timer_block_item.TimerBlockItem.toggle_expand(), and trigger_block_item.TriggerBlockItem.toggle_expand().
toggle_expand
action_block_item.ActionBlockItem.toggle_expand
Definition at line 94 of file action_block_item.py.
toggle_proxy
action_block_item.ActionBlockItem.toggle_proxy = QGraphicsProxyWidget(self)
Definition at line 96 of file action_block_item.py.
width
action_block_item.ActionBlockItem.width = conf.BLOCK_WIDTH
Definition at line 37 of file action_block_item.py.
Referenced by boundingRect(), condition_block_item.ConditionBlockItem.boundingRect(), script_block_item.ScriptBlockItem.boundingRect(), sensor_block_item.SensorBlockItem.boundingRect(), timer_block_item.TimerBlockItem.boundingRect(), trigger_block_item.TriggerBlockItem.boundingRect(), paint(), condition_block_item.ConditionBlockItem.paint(), script_block_item.ScriptBlockItem.paint(), sensor_block_item.SensorBlockItem.paint(), timer_block_item.TimerBlockItem.paint(), and trigger_block_item.TriggerBlockItem.paint().
The documentation for this class was generated from the following file:
C:/Users/J.Zanella/Desktop/ESPHomeGUIeasy/gui/action_block_item.py