ESPHomeGUIeasy: yaml_highlighter.YamlHighlighter Class Reference
yaml_highlighter.YamlHighlighter Class Reference
Public Member Functions
__init__ (self, document)
highlightBlock (self, text)
Public Attributes
key_format = QTextCharFormat()
string_format = QTextCharFormat()
number_format = QTextCharFormat()
boolean_format = QTextCharFormat()
null_format = QTextCharFormat()
list_format = QTextCharFormat()
comment_format = QTextCharFormat()
indent_format = QTextCharFormat()
list rules
Detailed Description
@class YamlHighlighter
@brief Evidenziatore sintattico per YAML in stile VS Code (dark mode).
Supporta evidenziazione per: chiavi, stringhe, numeri, booleani, null, liste, commenti.
Definition at line 4 of file yaml_highlighter.py.
Constructor & Destructor Documentation
__init__()
yaml_highlighter.YamlHighlighter.__init__ (self, document)
Definition at line 11 of file yaml_highlighter.py.
    def __init__(self, document):
        super().__init__(document)
        # Formati base
        self.key_format = QTextCharFormat()
        self.key_format.setForeground(QColor("#569CD6"))  # blu chiavi
        self.string_format = QTextCharFormat()
        self.string_format.setForeground(QColor("#CE9178"))  # rosso stringhe
        self.number_format = QTextCharFormat()
        self.number_format.setForeground(QColor("#B5CEA8"))  # verde numeri
        self.boolean_format = QTextCharFormat()
        self.boolean_format.setForeground(QColor("#DCDCAA"))  # giallo booleani
        self.null_format = QTextCharFormat()
        self.null_format.setForeground(QColor("#808080"))  # grigio null
        self.list_format = QTextCharFormat()
        self.list_format.setForeground(QColor("#9CDCFE"))  # celeste liste
        self.comment_format = QTextCharFormat()
        self.comment_format.setForeground(QColor("#6A9955"))  # verde commenti
        self.indent_format = QTextCharFormat()
        self.indent_format.setForeground(QColor("#404040"))  # grigio indentazione
        # Regole di evidenziazione (ordine conta!)
        self.rules = [
            (re.compile(r'^\s*[\w\-\.]+:'), self.key_format),  # chiavi
            (re.compile(r':\s*".*?"'), self.string_format),
            (re.compile(r":\s*\'.*?\'"), self.string_format),
            (re.compile(r":\s*\d+"), self.number_format),
            (re.compile(r":\s*(true|false)\b", re.IGNORECASE), self.boolean_format),
            (re.compile(r":\s*null\b", re.IGNORECASE), self.null_format),
            (re.compile(r'^\s*-\s.*'), self.list_format),  # liste
            (re.compile(r'#.*$'), self.comment_format)
        ]
References __init__().
Referenced by __init__().
Member Function Documentation
highlightBlock()
yaml_highlighter.YamlHighlighter.highlightBlock (self, text)
Definition at line 51 of file yaml_highlighter.py.
    def highlightBlock(self, text):
        # Evidenzia indentazione (opzionale, solo spazi iniziali)
        match_indent = re.match(r'^(\s+)', text)
        if match_indent:
            start, end = match_indent.span(1)
            self.setFormat(start, end - start, self.indent_format)
        for pattern, fmt in self.rules:
            for match in pattern.finditer(text):
                start, end = match.span()
                self.setFormat(start, end - start, fmt)
References indent_format, and rules.
Member Data Documentation
boolean_format
yaml_highlighter.YamlHighlighter.boolean_format = QTextCharFormat()
Definition at line 24 of file yaml_highlighter.py.
comment_format
yaml_highlighter.YamlHighlighter.comment_format = QTextCharFormat()
Definition at line 33 of file yaml_highlighter.py.
indent_format
yaml_highlighter.YamlHighlighter.indent_format = QTextCharFormat()
Definition at line 36 of file yaml_highlighter.py.
Referenced by highlightBlock().
key_format
yaml_highlighter.YamlHighlighter.key_format = QTextCharFormat()
Definition at line 15 of file yaml_highlighter.py.
list_format
yaml_highlighter.YamlHighlighter.list_format = QTextCharFormat()
Definition at line 30 of file yaml_highlighter.py.
null_format
yaml_highlighter.YamlHighlighter.null_format = QTextCharFormat()
Definition at line 27 of file yaml_highlighter.py.
number_format
yaml_highlighter.YamlHighlighter.number_format = QTextCharFormat()
Definition at line 21 of file yaml_highlighter.py.
rules
list yaml_highlighter.YamlHighlighter.rules
Initial value:
=  [
            (re.compile(r'^\s*[\w\-\.]+:'), self.key_format),  # chiavi
            (re.compile(r':\s*".*?"'), self.string_format),
            (re.compile(r":\s*\'.*?\'"), self.string_format),
            (re.compile(r":\s*\d+"), self.number_format),
            (re.compile(r":\s*(true|false)\b", re.IGNORECASE), self.boolean_format),
            (re.compile(r":\s*null\b", re.IGNORECASE), self.null_format),
            (re.compile(r'^\s*-\s.*'), self.list_format),  # liste
            (re.compile(r'#.*$'), self.comment_format)
        ]
Definition at line 40 of file yaml_highlighter.py.
Referenced by highlightBlock().
string_format
yaml_highlighter.YamlHighlighter.string_format = QTextCharFormat()
Definition at line 18 of file yaml_highlighter.py.
The documentation for this class was generated from the following file:
core/yaml_highlighter.py