ESPHomeGUIeasy: project_handler.ImportWorker Class Reference
project_handler.ImportWorker Class Reference
Public Member Functions
__init__ (self, path_zip, path_dest)
run (self)
Public Attributes
path_zip = path_zip
path_dest = path_dest
Static Public Attributes
progress = pyqtSignal(int, int)
finished = pyqtSignal(str, str)
Detailed Description
@brief Qt worker class for importing ESPHome projects from a ZIP archive.
Extracts files to a destination folder and tries to locate a `.yaml` file to open automatically.
@signal progress(current: int, total: int): Emits progress percentage during extraction.
@signal finished(path_yaml: str, path_zip: str): Emits the YAML path once import is complete.
Definition at line 27 of file project_handler.py.
Constructor & Destructor Documentation
__init__()
project_handler.ImportWorker.__init__ (self, path_zip, path_dest)
Definition at line 39 of file project_handler.py.
    def __init__(self, path_zip, path_dest):
        super().__init__()
        self.path_zip = path_zip
        self.path_dest = path_dest
References __init__().
Referenced by __init__().
Member Function Documentation
run()
project_handler.ImportWorker.run (self)
Definition at line 44 of file project_handler.py.
    def run(self):
        import os, zipfile
        base_name = os.path.splitext(os.path.basename(self.path_zip))[0]
        final_proj_dir = os.path.join(self.path_dest, base_name)
        os.makedirs(final_proj_dir, exist_ok=True)
        yaml_found = None
        try:
            with zipfile.ZipFile(self.path_zip, 'r') as zipf:
                filelist = zipf.namelist()
                total = len(filelist)
                for i, member in enumerate(filelist, 1):
                    zipf.extract(member, final_proj_dir)
                    self.progress.emit(i, total)
            for root, dirs, files in os.walk(final_proj_dir):
                for file in files:
                    if file.endswith(".yaml") or file.endswith(".yml"):
                        yaml_found = os.path.join(root, file)
                        break
                if yaml_found:
                    break
        except Exception as e:
            yaml_found = None
        self.finished.emit(yaml_found or "", self.path_zip)
References finished, path_dest, path_zip, and progress.
Member Data Documentation
finished
project_handler.ImportWorker.finished = pyqtSignal(str, str) static
Definition at line 37 of file project_handler.py.
Referenced by project_handler.ExportWorker.run(), and run().
path_dest
project_handler.ImportWorker.path_dest = path_dest
Definition at line 42 of file project_handler.py.
Referenced by run().
path_zip
project_handler.ImportWorker.path_zip = path_zip
Definition at line 41 of file project_handler.py.
Referenced by project_handler.ExportWorker.run(), and run().
progress
project_handler.ImportWorker.progress = pyqtSignal(int, int) static
Definition at line 36 of file project_handler.py.
Referenced by splash_screen.SplashScreen.advance(), project_handler.ExportWorker.run(), and run().
The documentation for this class was generated from the following file:
C:/Users/J.Zanella/Desktop/ESPHomeGUIeasy/core/project_handler.py