ESPHomeGUIeasy: yaml_editor.YamlCodeEditor Class Reference
yaml_editor.YamlCodeEditor Class Reference
Public Member Functions
__init__ (self)
line_number_area_size (self)
update_line_number_area_width (self, _)
update_line_number_area (self, rect, dy)
resizeEvent (self, event)
line_number_area_paint (self, event)
highlight_current_line (self)
Public Attributes
line_number_area = LineNumberArea(self)
update_line_number_area_width
update_line_number_area
highlight_current_line
Detailed Description
@brief Extended text editor for YAML with line numbers and line highlighting.
Provides an enhanced editing experience, similar to modern code editors:
- Displays line numbers
- Highlights the current line
- Disables word wrapping
Definition at line 58 of file yaml_editor.py.
Constructor & Destructor Documentation
__init__()
yaml_editor.YamlCodeEditor.__init__ (self)
@brief Initializes the YAML code editor with line numbers and highlighting.
Connects signals to handle editor resizing, text block changes,
and cursor movement. Disables line wrapping.
Definition at line 67 of file yaml_editor.py.
    def __init__(self):
        """
        @brief Initializes the YAML code editor with line numbers and highlighting.
        Connects signals to handle editor resizing, text block changes,
        and cursor movement. Disables line wrapping.
        """
        super().__init__()
        self.line_number_area = LineNumberArea(self)
        self.line_number_area.setStyleSheet("background-color: #1e1e1e;")
        self.blockCountChanged.connect(self.update_line_number_area_width)
        self.updateRequest.connect(self.update_line_number_area)
        self.cursorPositionChanged.connect(self.highlight_current_line)
        self.update_line_number_area_width(0)
        self.highlight_current_line()
        self.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
References __init__().
Referenced by __init__().
Member Function Documentation
highlight_current_line()
yaml_editor.YamlCodeEditor.highlight_current_line (self)
@brief Highlights the background of the current line (if not read-only).
Uses a subtle dark color for better text tracking.
Definition at line 166 of file yaml_editor.py.
    def highlight_current_line(self):
        """
        @brief Highlights the background of the current line (if not read-only).
        Uses a subtle dark color for better text tracking.
        """
        extraSelections = []
        if not self.isReadOnly():
            selection = QTextEdit.ExtraSelection()
            # Crea un nuovo formato basato sullo stile corrente del testo
            format = QTextCharFormat(self.currentCharFormat())
            format.setBackground(QColor("#2a2d2e"))  # colore scuro stile VS Code
            selection.format = format
            selection.cursor = self.textCursor()
            selection.cursor.clearSelection()
            extraSelections.append(selection)
        self.setExtraSelections(extraSelections)
line_number_area_paint()
yaml_editor.YamlCodeEditor.line_number_area_paint (self, event)
@brief Custom paint method for rendering line numbers.
Iterates over visible text blocks and draws their line numbers
in the left margin.
@param event Paint event describing the updated region.
Definition at line 136 of file yaml_editor.py.
    def line_number_area_paint(self, event):
        """
        @brief Custom paint method for rendering line numbers.
        Iterates over visible text blocks and draws their line numbers
        in the left margin.
        @param event Paint event describing the updated region.
        """
        painter = QPainter(self.line_number_area)
        painter.fillRect(event.rect(), Qt.GlobalColor.darkGray)
        block = self.firstVisibleBlock()
        block_number = block.blockNumber()
        top = int(self.blockBoundingGeometry(block).translated(self.contentOffset()).top())
        bottom = top + int(self.blockBoundingRect(block).height())
        while block.isValid() and top <= event.rect().bottom():
            if block.isVisible() and bottom >= event.rect().top():
                number = str(block_number + 1)
                painter.setPen(Qt.GlobalColor.white)
                painter.drawText(0, top, self.line_number_area.width() - 4, self.fontMetrics().height(),
                                 Qt.AlignmentFlag.AlignRight, number)
            block = block.next()
            top = bottom
            bottom = top + int(self.blockBoundingRect(block).height())
            block_number += 1
References line_number_area.
line_number_area_size()
yaml_editor.YamlCodeEditor.line_number_area_size (self)
@brief Calculates the width needed to display all line numbers.
Depends on the number of digits in the total line count.
@return QSize with calculated width.
Definition at line 87 of file yaml_editor.py.
    def line_number_area_size(self):
        """
        @brief Calculates the width needed to display all line numbers.
        Depends on the number of digits in the total line count.
        @return QSize with calculated width.
        """
        digits = len(str(max(1, self.blockCount())))
        space = 3 + self.fontMetrics().horizontalAdvance('9') * digits
        return QSize(space, 0)
Referenced by resizeEvent(), and update_line_number_area_width().
resizeEvent()
yaml_editor.YamlCodeEditor.resizeEvent (self, event)
@brief Repositions the line number area on editor resize.
Ensures the number area stays aligned with the editor content.
@param event Resize event.
Definition at line 124 of file yaml_editor.py.
    def resizeEvent(self, event):
        """
        @brief Repositions the line number area on editor resize.
        Ensures the number area stays aligned with the editor content.
        @param event Resize event.
        """
        super().resizeEvent(event)
        cr = self.contentsRect()
        self.line_number_area.setGeometry(QRect(cr.left(), cr.top(), self.line_number_area_size().width(), cr.height()))
References line_number_area, line_number_area_size(), and resizeEvent().
Referenced by resizeEvent().
update_line_number_area()
yaml_editor.YamlCodeEditor.update_line_number_area (self, rect, dy)
@brief Updates/redraws the line number area when the editor changes.
Handles vertical scrolling and full redraw requests.
@param rect QRect describing the affected area.
@param dy Vertical delta scroll (0 if full repaint is needed).
Definition at line 107 of file yaml_editor.py.
    def update_line_number_area(self, rect, dy):
        """
        @brief Updates/redraws the line number area when the editor changes.
        Handles vertical scrolling and full redraw requests.
        @param rect QRect describing the affected area.
        @param dy Vertical delta scroll (0 if full repaint is needed).
        """
        if dy:
            self.line_number_area.scroll(0, dy)
        else:
            self.line_number_area.update(0, rect.y(), self.line_number_area.width(), rect.height())
        if rect.contains(self.viewport().rect()):
            self.update_line_number_area_width(0)
References line_number_area, and update_line_number_area_width.
update_line_number_area_width()
yaml_editor.YamlCodeEditor.update_line_number_area_width (self, _)
@brief Adjusts the left margin of the editor to fit the line number area.
Called whenever the number of blocks (lines) changes.
Definition at line 99 of file yaml_editor.py.
    def update_line_number_area_width(self, _):
        """
        @brief Adjusts the left margin of the editor to fit the line number area.
        Called whenever the number of blocks (lines) changes.
        """
        self.setViewportMargins(self.line_number_area_size().width(), 0, 0, 0)
References line_number_area_size().
Member Data Documentation
highlight_current_line
yaml_editor.YamlCodeEditor.highlight_current_line
Definition at line 80 of file yaml_editor.py.
line_number_area
yaml_editor.YamlCodeEditor.line_number_area = LineNumberArea(self)
Definition at line 75 of file yaml_editor.py.
Referenced by line_number_area_paint(), resizeEvent(), and update_line_number_area().
update_line_number_area
yaml_editor.YamlCodeEditor.update_line_number_area
Definition at line 79 of file yaml_editor.py.
update_line_number_area_width
yaml_editor.YamlCodeEditor.update_line_number_area_width
Definition at line 78 of file yaml_editor.py.
Referenced by update_line_number_area().
The documentation for this class was generated from the following file:
C:/Users/J.Zanella/Desktop/ESPHomeGUIeasy/gui/yaml_editor.py