ESPHomeGUIeasy: progress_dialog.ProgressDialog Class Reference
progress_dialog.ProgressDialog Class Reference
Public Member Functions
__init__ (self, title="Operazione in corso...", label_text="Elaborazione file...", parent=None)
set_progress (self, value, maximum)
set_indeterminate (self)
Public Attributes
label = QLabel(label_text)
progress_bar = QProgressBar()
Detailed Description
@brief Modal dialog showing a progress bar and status label.
Used to provide visual feedback during long-running operations.
Definition at line 20 of file progress_dialog.py.
Constructor & Destructor Documentation
__init__()
progress_dialog.ProgressDialog.__init__ (self, title = "Operazione in corso...", label_text = "Elaborazione file...", parent = None)
Definition at line 26 of file progress_dialog.py.
    def __init__(self, title="Operazione in corso...", label_text="Elaborazione file...", parent=None):
        super().__init__(parent)
        self.setWindowTitle(title)
        layout = QVBoxLayout(self)
        self.label = QLabel(label_text)
        layout.addWidget(self.label)
        self.progress_bar = QProgressBar()
        layout.addWidget(self.progress_bar)
        self.setLayout(layout)
        self.setModal(True)
        self.setFixedWidth(400)
        self.progress_bar.setValue(0)
References __init__().
Referenced by __init__().
Member Function Documentation
set_indeterminate()
progress_dialog.ProgressDialog.set_indeterminate (self)
Definition at line 43 of file progress_dialog.py.
    def set_indeterminate(self):
        # Barra animata indeterminata (marquee)
        self.progress_bar.setMaximum(0)
        self.progress_bar.setValue(0)
References progress_bar.
set_progress()
progress_dialog.ProgressDialog.set_progress (self, value, maximum)
Definition at line 39 of file progress_dialog.py.
    def set_progress(self, value, maximum):
        self.progress_bar.setMaximum(maximum)
        self.progress_bar.setValue(value)
References progress_bar.
Member Data Documentation
label
progress_dialog.ProgressDialog.label = QLabel(label_text)
Definition at line 30 of file progress_dialog.py.
progress_bar
progress_dialog.ProgressDialog.progress_bar = QProgressBar()
Definition at line 32 of file progress_dialog.py.
Referenced by set_indeterminate(), and set_progress().
The documentation for this class was generated from the following file:
C:/Users/J.Zanella/Desktop/ESPHomeGUIeasy/gui/progress_dialog.py