ESPHomeGUIeasy: collapsible_section.CollapsibleSection Class Reference
collapsible_section.CollapsibleSection Class Reference
Public Member Functions
__init__ (self, str title, QWidget content, str icon="")
on_toggled (self, checked)
set_title (self, title)
Public Attributes
toggle_button = QToolButton(text=f"{icon} {title}", checkable=True, checked=False)
on_toggled
content_area = QFrame()
Protected Attributes
_icon = icon
Detailed Description
@brief A collapsible panel widget that can show or hide its content with a toggle button.
Includes an arrow icon indicating expansion state, and supports a text title with optional icon.
Definition at line 24 of file collapsible_section.py.
Constructor & Destructor Documentation
__init__()
collapsible_section.CollapsibleSection.__init__ (self, str title, QWidget content, str icon = "")
@brief Initializes the collapsible section with a title, content widget, and optional icon.
@param title The header text to display.
@param content The QWidget to show or hide inside the section.
@param icon Optional string icon (e.g. emoji) to show before the title.
Definition at line 30 of file collapsible_section.py.
    def __init__(self, title: str, content: QWidget, icon: str = ""):
        """
        @brief Initializes the collapsible section with a title, content widget, and optional icon.
        @param title The header text to display.
        @param content The QWidget to show or hide inside the section.
        @param icon Optional string icon (e.g. emoji) to show before the title.
        """
        super().__init__()
        self._icon = icon  # <--- salva l’icona come attributo di istanza
        self.toggle_button = QToolButton(text=f"{icon} {title}", checkable=True, checked=False)
        self.toggle_button.setStyleSheet(Pantone.ACCORDION_QTOOLBUTTON)
        self.toggle_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toggle_button.setArrowType(Qt.ArrowType.RightArrow)
        self.toggle_button.toggled.connect(self.on_toggled)
        self.toggle_button.setStyleSheet(Pantone.ACCORDION_HEADER_STYLE)
        self.toggle_button.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        self.content_area = QFrame()
        self.content_area.setFrameShape(QFrame.Shape.NoFrame)
        self.content_area.setMaximumHeight(0)
        self.content_area.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        self.content_area.setStyleSheet("background-color: #2a2d2e; border-radius: 0 0 8px 8px;")
        lay = QVBoxLayout(self)
        lay.setContentsMargins(0, 0, 0, 0)
        lay.addWidget(self.toggle_button)
        lay.addWidget(self.content_area)
        # Set layout for content
        content_layout = QVBoxLayout()
        content_layout.addWidget(content)
        content_layout.setContentsMargins(0, 0, 0, 0)  # Imposta sempre a zero
        self.content_area.setLayout(content_layout)
References __init__().
Referenced by __init__().
Member Function Documentation
on_toggled()
collapsible_section.CollapsibleSection.on_toggled (self, checked)
@brief Slot connected to the toggle button to expand or collapse the content area.
@param checked True if expanded, False if collapsed.
Definition at line 65 of file collapsible_section.py.
    def on_toggled(self, checked):
        """
        @brief Slot connected to the toggle button to expand or collapse the content area.
        @param checked True if expanded, False if collapsed.
        """
        if checked:
            self.toggle_button.setArrowType(Qt.ArrowType.DownArrow)
            self.content_area.setMaximumHeight(16777215)
        else:
            self.toggle_button.setArrowType(Qt.ArrowType.RightArrow)
            self.content_area.setMaximumHeight(0)
        self.updateGeometry()
References content_area, and toggle_button.
set_title()
collapsible_section.CollapsibleSection.set_title (self, title)
@brief Updates the section title text, preserving the icon.
@param title New text for the header.
Definition at line 79 of file collapsible_section.py.
    def set_title(self, title):
        """
        @brief Updates the section title text, preserving the icon.
        @param title New text for the header.
        """
        self.toggle_button.setText(f"{self._icon} {title}")
References toggle_button.
Member Data Documentation
_icon
collapsible_section.CollapsibleSection._icon = icon protected
Definition at line 39 of file collapsible_section.py.
content_area
collapsible_section.CollapsibleSection.content_area = QFrame()
Definition at line 48 of file collapsible_section.py.
Referenced by on_toggled().
on_toggled
collapsible_section.CollapsibleSection.on_toggled
Definition at line 44 of file collapsible_section.py.
toggle_button
collapsible_section.CollapsibleSection.toggle_button = QToolButton(text=f"{icon} {title}", checkable=True, checked=False)
Definition at line 40 of file collapsible_section.py.
Referenced by on_toggled(), and set_title().
The documentation for this class was generated from the following file:
C:/Users/J.Zanella/Desktop/ESPHomeGUIeasy/gui/collapsible_section.py