ESPHomeGUIeasy: menu_bar.MainMenuBar Class Reference
menu_bar.MainMenuBar Class Reference
Public Member Functions
__init__ (self, parent=None)
update_labels (self)
create_menus (self)
show_about_dialog (self)
open_project_gallery_window (self)
open_user_project_gallery_window (self)
open_full_settings_dialog (self)
open_docs (self)
Public Attributes
main_window = parent
list recent_file_actions = []
file_menu = self.addMenu(Translator.tr("menu_file"))
header_action_proj = QWidgetAction(self)
label_proj = QLabel(f"📁 {Translator.tr('menu_header_projects')}")
new_action = QAction("🆕 " + Translator.tr("new_project"), self)
import_project_action = QAction("📂 " + Translator.tr("import_project"), self)
export_project_action = QAction("📄 " + Translator.tr("export_project"), self)
header_action_yaml = QWidgetAction(self)
label_yaml = QLabel(f"📄 {Translator.tr('menu_header_yaml')}")
open_action = QAction("📁 " + Translator.tr("open_project"), self)
save_action = QAction("📂 " + Translator.tr("save_project"), self)
saveas_action = QAction("📁 " + Translator.tr("save_as"), self)
import_action = QAction("📅 " + Translator.tr("import_yaml"), self)
export_action = QAction("📄 " + Translator.tr("export_yaml"), self)
exit_action = QAction("❌ " + Translator.tr("exit"), self)
project_menu = self.addMenu(Translator.tr("menu_progetti"))
community_project_action = QAction(Translator.tr("progetti_community"), self)
open_project_gallery_window
user_projects_action = QAction(Translator.tr("user_projects_title"), self)
open_user_project_gallery_window
settings_menu = self.addMenu(Translator.tr("menu_settings"))
full_settings_action = QAction(Translator.tr("menu_full_settings"), self)
open_full_settings_dialog
about_action = QAction(Translator.tr("menu_about"), self)
show_about_dialog
docs_action = QAction(Translator.tr("menu_documentation"), self)
open_docs
Protected Member Functions
_update_recent_files_menu (self)
_open_recent_file (self, str path)
_make_open_file_handler (self, str path)
Protected Attributes
_project_gallery_window = ProjectGalleryWindow()
_user_project_gallery_window = None
Detailed Description
@brief Implements the application’s main menu bar with various menus and actions.
Creates and updates menus dynamically, manages recent files,
and provides dialogs for settings, project galleries, and about info.
Definition at line 32 of file menu_bar.py.
Constructor & Destructor Documentation
__init__()
menu_bar.MainMenuBar.__init__ (self, parent = None)
Definition at line 39 of file menu_bar.py.
    def __init__(self, parent=None):
        super().__init__(parent)
        self.main_window = parent
        self.setStyleSheet(Pantone.MENU_BAR)
        self.recent_file_actions = []
        self.create_menus()
References __init__().
Referenced by __init__().
Member Function Documentation
_make_open_file_handler()
menu_bar.MainMenuBar._make_open_file_handler (self, str path) protected
Definition at line 183 of file menu_bar.py.
    def _make_open_file_handler(self, path: str):
        return lambda checked=False: self._open_recent_file(path)
References _open_recent_file().
Referenced by _update_recent_files_menu().
_open_recent_file()
menu_bar.MainMenuBar._open_recent_file (self, str path) protected
Definition at line 178 of file menu_bar.py.
    def _open_recent_file(self, path: str):
        parent = self.parent()
        if parent and callable(getattr(parent, "open_project", None)):
            parent.open_project(path)
Referenced by _make_open_file_handler().
_update_recent_files_menu()
menu_bar.MainMenuBar._update_recent_files_menu (self) protected
Definition at line 163 of file menu_bar.py.
    def _update_recent_files_menu(self):
        for act in self.recent_file_actions:
            self.file_menu.removeAction(act)
        self.recent_file_actions.clear()
        recent_files = get_recent_files(limit=4)
        if recent_files:
            self.file_menu.addSeparator()
            for path, name in recent_files:
                action = QAction(name, self)
                action.setToolTip(path)
                action.triggered.connect(self._make_open_file_handler(path))
                self.file_menu.addAction(action)
                self.recent_file_actions.append(action)
References _make_open_file_handler(), file_menu, and recent_file_actions.
create_menus()
menu_bar.MainMenuBar.create_menus (self)
Definition at line 50 of file menu_bar.py.
    def create_menus(self):
        parent = self.parent()
        # FILE MENU
        self.file_menu = self.addMenu(Translator.tr("menu_file"))
        self.header_action_proj = QWidgetAction(self)
        self.label_proj = QLabel(f"📁 {Translator.tr('menu_header_projects')}")
        self.label_proj.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_proj.setStyleSheet("""
            QLabel {
                background-color: #2c2c2c;
                color: #ffffff;
                font-weight: bold;
                padding: 6px;
                border-top: 1px solid #555;
                border-bottom: 1px solid #555;
            }
        """)
        self.header_action_proj.setDefaultWidget(self.label_proj)
        self.file_menu.addAction(self.header_action_proj)
        self.new_action = QAction("🆕 " + Translator.tr("new_project"), self)
        self.new_action.setShortcut("Ctrl+N")
        self.new_action.triggered.connect(self.main_window.nuovo_progetto)
        self.file_menu.addAction(self.new_action)
        self.import_project_action = QAction("📂 " + Translator.tr("import_project"), self)
        self.import_project_action.triggered.connect(parent.import_project)
        self.file_menu.addAction(self.import_project_action)
        self.export_project_action = QAction("📄 " + Translator.tr("export_project"), self)
        self.export_project_action.triggered.connect(parent.export_project)
        self.file_menu.addAction(self.export_project_action)
        self.file_menu.addSeparator()
        self.header_action_yaml = QWidgetAction(self)
        self.label_yaml = QLabel(f"📄 {Translator.tr('menu_header_yaml')}")
        self.label_yaml.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_yaml.setStyleSheet("""
            QLabel {
                background-color: #2c2c2c;
                color: #ffffff;
                font-weight: bold;
                padding: 6px;
                border-top: 1px solid #555;
                border-bottom: 1px solid #555;
            }
        """)
        self.header_action_yaml.setDefaultWidget(self.label_yaml)
        self.file_menu.addAction(self.header_action_yaml)
        self.open_action = QAction("📁 " + Translator.tr("open_project"), self)
        self.open_action.setShortcut("Ctrl+O")
        self.open_action.triggered.connect(lambda _: parent.open_project_dialog())
        self.file_menu.addAction(self.open_action)
        self.save_action = QAction("📂 " + Translator.tr("save_project"), self)
        self.save_action.setShortcut("Ctrl+S")
        self.save_action.triggered.connect(parent.salva_progetto)
        self.file_menu.addAction(self.save_action)
        self.saveas_action = QAction("📁 " + Translator.tr("save_as"), self)
        self.saveas_action.setShortcut("Ctrl+Shift+S")
        self.saveas_action.triggered.connect(parent.salva_con_nome)
        self.file_menu.addAction(self.saveas_action)
        self.import_action = QAction("📅 " + Translator.tr("import_yaml"), self)
        self.import_action.triggered.connect(parent.importa_yaml)
        self.file_menu.addAction(self.import_action)
        self.export_action = QAction("📄 " + Translator.tr("export_yaml"), self)
        self.export_action.triggered.connect(parent.esporta_yaml)
        self.file_menu.addAction(self.export_action)
        self.file_menu.addSeparator()
        self.exit_action = QAction("❌ " + Translator.tr("exit"), self)
        self.exit_action.setShortcut("Ctrl+Q")
        self.exit_action.triggered.connect(parent.close)
        self.file_menu.addAction(self.exit_action)
        self._update_recent_files_menu()
        # PROJECT MENU
        self.project_menu = self.addMenu(Translator.tr("menu_progetti"))
        self.community_project_action = QAction(Translator.tr("progetti_community"), self)
        self.community_project_action.triggered.connect(self.open_project_gallery_window)
        self.project_menu.addAction(self.community_project_action)
        self.user_projects_action = QAction(Translator.tr("user_projects_title"), self)
        self.user_projects_action.triggered.connect(self.open_user_project_gallery_window)
        self.project_menu.addAction(self.user_projects_action)
        # SETTINGS MENU
        self.settings_menu = self.addMenu(Translator.tr("menu_settings"))
        self.full_settings_action = QAction(Translator.tr("menu_full_settings"), self)
        self.full_settings_action.triggered.connect(self.open_full_settings_dialog)
        self.settings_menu.addAction(self.full_settings_action)
        # HELP MENU
        help_menu = self.addMenu("❓")
        self.about_action = QAction(Translator.tr("menu_about"), self)
        self.about_action.triggered.connect(self.show_about_dialog)
        help_menu.addAction(self.about_action)
        self.docs_action = QAction(Translator.tr("menu_documentation"), self)
        self.docs_action.triggered.connect(self.open_docs)
        help_menu.addAction(self.docs_action)
Referenced by update_labels().
open_docs()
menu_bar.MainMenuBar.open_docs (self)
@brief Opens the local Doxygen documentation in the default web browser.
Definition at line 247 of file menu_bar.py.
    def open_docs(self):
        """
        @brief Opens the local Doxygen documentation in the default web browser.
        """
        doc_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../docs/html/index.html"))
        if os.path.exists(doc_path):
            webbrowser.open_new_tab(f"file://{doc_path}")
        else:
            QMessageBox.warning(None, Translator.tr("menu_documentation"), Translator.tr("error_docs_not_found"))
open_full_settings_dialog()
menu_bar.MainMenuBar.open_full_settings_dialog (self)
Definition at line 243 of file menu_bar.py.
    def open_full_settings_dialog(self):
        dlg = SettingsDialog(self)
        dlg.exec()
open_project_gallery_window()
menu_bar.MainMenuBar.open_project_gallery_window (self)
Definition at line 222 of file menu_bar.py.
    def open_project_gallery_window(self):
        if not hasattr(self, "_project_gallery_window") or self._project_gallery_window is None:
            self._project_gallery_window = ProjectGalleryWindow()
        self._project_gallery_window.show()
        self._project_gallery_window.raise_()
        self._project_gallery_window.activateWindow()
References _project_gallery_window.
open_user_project_gallery_window()
menu_bar.MainMenuBar.open_user_project_gallery_window (self)
Definition at line 229 of file menu_bar.py.
    def open_user_project_gallery_window(self):
        # Se l'oggetto esiste ma è stato chiuso, lo azzero
        if hasattr(self, "_user_project_gallery_window"):
            if self._user_project_gallery_window is not None and not self._user_project_gallery_window.isVisible():
                self._user_project_gallery_window = None
        if not hasattr(self, "_user_project_gallery_window") or self._user_project_gallery_window is None:
            self._user_project_gallery_window = UserProjectManagerWindow(main_window=self.main_window)
        self._user_project_gallery_window.show()
        self._user_project_gallery_window.raise_()
        self._user_project_gallery_window.activateWindow()
References _user_project_gallery_window.
show_about_dialog()
menu_bar.MainMenuBar.show_about_dialog (self)
Definition at line 186 of file menu_bar.py.
    def show_about_dialog(self):
        version = getattr(conf, "APP_VERSION", "1.0.0")
        release_date = getattr(conf, "APP_RELEASE_DATE", "2025-05-30")
        icon_path = getattr(conf, "SW_ICON_PATH", "")
        dlg = QDialog(self)
        dlg.setWindowTitle("Informazioni su ESPHomeGuiEasy")
        dlg.setStyleSheet(Pantone.DIALOG_STYLE)
        layout = QVBoxLayout()
        if os.path.exists(icon_path):
            pix = QPixmap(icon_path).scaled(90, 90)
            lbl_logo = QLabel()
            lbl_logo.setPixmap(pix)
            lbl_logo.setAlignment(Qt.AlignmentFlag.AlignCenter)
            layout.addWidget(lbl_logo)
        else:
            layout.addWidget(QLabel("ESPHomeGuiEasy"))
        lbl_info = QLabel(
            f"<b>ESPHomeGuiEasy</b><br>"
            f"Versione: <b>{version}</b><br>"
            f"Data rilascio: <b>{release_date}</b><br><br>"
            f"Copyright (c) 2025 Juri<br>"
            f"Licenza: AGPLv3 - Uso non commerciale"
        )
        lbl_info.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(lbl_info)
        btn = QPushButton("Chiudi")
        btn.clicked.connect(dlg.accept)
        layout.addWidget(btn, alignment=Qt.AlignmentFlag.AlignCenter)
        dlg.setLayout(layout)
        dlg.exec()
update_labels()
menu_bar.MainMenuBar.update_labels (self)
Definition at line 46 of file menu_bar.py.
    def update_labels(self):
        self.clear()
        self.create_menus()
References create_menus().
Member Data Documentation
_project_gallery_window
menu_bar.MainMenuBar._project_gallery_window = ProjectGalleryWindow() protected
Definition at line 224 of file menu_bar.py.
Referenced by open_project_gallery_window().
_user_project_gallery_window
menu_bar.MainMenuBar._user_project_gallery_window = None protected
Definition at line 233 of file menu_bar.py.
Referenced by open_user_project_gallery_window().
about_action
menu_bar.MainMenuBar.about_action = QAction(Translator.tr("menu_about"), self)
Definition at line 154 of file menu_bar.py.
community_project_action
menu_bar.MainMenuBar.community_project_action = QAction(Translator.tr("progetti_community"), self)
Definition at line 137 of file menu_bar.py.
docs_action
menu_bar.MainMenuBar.docs_action = QAction(Translator.tr("menu_documentation"), self)
Definition at line 158 of file menu_bar.py.
exit_action
menu_bar.MainMenuBar.exit_action = QAction("❌ " + Translator.tr("exit"), self)
Definition at line 128 of file menu_bar.py.
export_action
menu_bar.MainMenuBar.export_action = QAction("📄 " + Translator.tr("export_yaml"), self)
Definition at line 122 of file menu_bar.py.
export_project_action
menu_bar.MainMenuBar.export_project_action = QAction("📄 " + Translator.tr("export_project"), self)
Definition at line 81 of file menu_bar.py.
file_menu
menu_bar.MainMenuBar.file_menu = self.addMenu(Translator.tr("menu_file"))
Definition at line 54 of file menu_bar.py.
Referenced by _update_recent_files_menu().
full_settings_action
menu_bar.MainMenuBar.full_settings_action = QAction(Translator.tr("menu_full_settings"), self)
Definition at line 147 of file menu_bar.py.
header_action_proj
menu_bar.MainMenuBar.header_action_proj = QWidgetAction(self)
Definition at line 56 of file menu_bar.py.
header_action_yaml
menu_bar.MainMenuBar.header_action_yaml = QWidgetAction(self)
Definition at line 87 of file menu_bar.py.
import_action
menu_bar.MainMenuBar.import_action = QAction("📅 " + Translator.tr("import_yaml"), self)
Definition at line 118 of file menu_bar.py.
import_project_action
menu_bar.MainMenuBar.import_project_action = QAction("📂 " + Translator.tr("import_project"), self)
Definition at line 77 of file menu_bar.py.
label_proj
menu_bar.MainMenuBar.label_proj = QLabel(f"📁 {Translator.tr('menu_header_projects')}")
Definition at line 57 of file menu_bar.py.
label_yaml
menu_bar.MainMenuBar.label_yaml = QLabel(f"📄 {Translator.tr('menu_header_yaml')}")
Definition at line 88 of file menu_bar.py.
main_window
menu_bar.MainMenuBar.main_window = parent
Definition at line 41 of file menu_bar.py.
Referenced by user_project_manager.UserProjectManagerWindow.apri_progetto().
new_action
menu_bar.MainMenuBar.new_action = QAction("🆕 " + Translator.tr("new_project"), self)
Definition at line 72 of file menu_bar.py.
open_action
menu_bar.MainMenuBar.open_action = QAction("📁 " + Translator.tr("open_project"), self)
Definition at line 103 of file menu_bar.py.
open_docs
menu_bar.MainMenuBar.open_docs
Definition at line 159 of file menu_bar.py.
open_full_settings_dialog
menu_bar.MainMenuBar.open_full_settings_dialog
Definition at line 148 of file menu_bar.py.
open_project_gallery_window
menu_bar.MainMenuBar.open_project_gallery_window
Definition at line 138 of file menu_bar.py.
open_user_project_gallery_window
menu_bar.MainMenuBar.open_user_project_gallery_window
Definition at line 142 of file menu_bar.py.
project_menu
menu_bar.MainMenuBar.project_menu = self.addMenu(Translator.tr("menu_progetti"))
Definition at line 136 of file menu_bar.py.
recent_file_actions
list menu_bar.MainMenuBar.recent_file_actions = []
Definition at line 43 of file menu_bar.py.
Referenced by _update_recent_files_menu().
save_action
menu_bar.MainMenuBar.save_action = QAction("📂 " + Translator.tr("save_project"), self)
Definition at line 108 of file menu_bar.py.
saveas_action
menu_bar.MainMenuBar.saveas_action = QAction("📁 " + Translator.tr("save_as"), self)
Definition at line 113 of file menu_bar.py.
settings_menu
menu_bar.MainMenuBar.settings_menu = self.addMenu(Translator.tr("menu_settings"))
Definition at line 146 of file menu_bar.py.
show_about_dialog
menu_bar.MainMenuBar.show_about_dialog
Definition at line 155 of file menu_bar.py.
user_projects_action
menu_bar.MainMenuBar.user_projects_action = QAction(Translator.tr("user_projects_title"), self)
Definition at line 141 of file menu_bar.py.
The documentation for this class was generated from the following file:
C:/Users/J.Zanella/Desktop/ESPHomeGUIeasy/gui/menu_bar.py