ESPHomeGUIeasy: log_handler.LOGHandler Class Reference
log_handler.LOGHandler Class Reference
Public Member Functions
__init__ (self, console_widget=None)
console (self)
log (self, message, level="info")
Protected Attributes
_console = console_widget
Detailed Description
Definition at line 10 of file log_handler.py.
Constructor & Destructor Documentation
__init__()
log_handler.LOGHandler.__init__ (self, console_widget = None)
Definition at line 11 of file log_handler.py.
    def __init__(self, console_widget=None):
        self._console = console_widget  # riferimento iniziale, ma non permanente
Member Function Documentation
console()
log_handler.LOGHandler.console (self)
Definition at line 15 of file log_handler.py.
    def console(self):
        # Cerca un QTextEdit attivo con nome console_output
        for w in QApplication.topLevelWidgets():
            if hasattr(w, "console_output"):
                return w.console_output
        return self._console  # fallback se non troviamo nulla
References _console.
Referenced by log_handler.GeneralLogHandler.log(), and log().
log()
log_handler.LOGHandler.log (self, message, level = "info")
Definition at line 22 of file log_handler.py.
    def log(self, message, level="info"):
        console = self.console
        if console is None:
            print(f"[{level.upper()}] {message}")
            return
        try:
            cursor = console.textCursor()
            if level == "error":
                color = "#ff5555"
            elif level == "warning":
                color = "#f1c40f"
            elif level == "success":
                color = "#33ff99"
            else:
                color = "#d4d4d4"
            html = f'<span style="color:{color};">[{level.upper()}]</span> {message}<br>'
            console.moveCursor(QTextCursor.MoveOperation.End)
            console.insertHtml(html)
            console.moveCursor(QTextCursor.MoveOperation.End)
        except RuntimeError:
            print(f"[LOGGER ERROR] QTextEdit distrutto. Messaggio:\n[{level.upper()}] {message}")
References console().
Member Data Documentation
_console
log_handler.LOGHandler._console = console_widget protected
Definition at line 12 of file log_handler.py.
Referenced by log_handler.GeneralLogHandler.console(), and console().
The documentation for this class was generated from the following file:
core/log_handler.py