ESPHomeGUIeasy: settings_db Namespace Reference
settings_db Namespace Reference
Functions
str get_user_db_path ()
init_db ()
set_setting (str key, str value)
str|None get_setting (str key)
add_recent_file (str path)
list[tuple[str, str]] get_recent_files (int limit=4)
Variables
logger = GeneralLogHandler()
Detailed Description
@file settings_db.py
@brief Provides functions to read and write user settings stored in a local SQLite database.
@defgroup core Core Modules
@ingroup main
@brief Core logic: YAML handling, logging, settings, flashing, etc.
Handles:
- Initialization of the `settings` and `recent_files` tables
- Get/set operations for key-value pairs in user config
- Storage of recently opened projects with timestamps
@version \ref PROJECT_NUMBER
@date July 2025
@license GNU Affero General Public License v3.0 (AGPLv3)
Function Documentation
add_recent_file()
settings_db.add_recent_file (str path)
@brief Adds or updates a recently opened file in the `recent_files` table.
@param path Absolute path to the YAML file.
Definition at line 99 of file settings_db.py.
def add_recent_file(path: str):
    """
    @brief Adds or updates a recently opened file in the `recent_files` table.
    @param path Absolute path to the YAML file.
    """
    filename = os.path.basename(path)
    conn = sqlite3.connect(get_user_db_path())
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO recent_files (path, filename, last_opened)
        VALUES (?, ?, CURRENT_TIMESTAMP)
        ON CONFLICT(path) DO UPDATE SET last_opened=CURRENT_TIMESTAMP, filename=excluded.filename
    """, (path, filename))
    conn.commit()
    conn.close()
References get_user_db_path().
get_recent_files()
list[tuple[str, str]] settings_db.get_recent_files (int limit = 4)
@brief Retrieves the most recently opened files from the database.
@param limit Maximum number of entries to return.
@return List of tuples (path, filename) ordered by last_opened descending.
Definition at line 117 of file settings_db.py.
def get_recent_files(limit: int = 4) -> list[tuple[str, str]]:
    """
    @brief Retrieves the most recently opened files from the database.
    @param limit Maximum number of entries to return.
    @return List of tuples (path, filename) ordered by last_opened descending.
    """
    conn = sqlite3.connect(get_user_db_path())
    cursor = conn.cursor()
    cursor.execute("""
        SELECT path, filename FROM recent_files
        ORDER BY last_opened DESC
        LIMIT ?
    """, (limit,))
    results = cursor.fetchall()
    conn.close()
    return results
References get_user_db_path().
get_setting()
str | None settings_db.get_setting (str key)
@brief Retrieves the value of a setting from the database.
@param key The setting name to look up.
@return The stored value, or None if not found or an error occurs.
Definition at line 81 of file settings_db.py.
def get_setting(key: str) -> str | None:
    """
    @brief Retrieves the value of a setting from the database.
    @param key The setting name to look up.
    @return The stored value, or None if not found or an error occurs.
    """
    try:
        conn = sqlite3.connect(get_user_db_path())
        cursor = conn.cursor()
        cursor.execute("SELECT value FROM settings WHERE key=?", (key,))
        result = cursor.fetchone()
        conn.close()
        return result[0].strip() if result and result[0].strip() else None
    except Exception:
        return None
References get_user_db_path().
get_user_db_path()
str settings_db.get_user_db_path ()
@brief Returns the absolute path to the user_config.db file in LOCALAPPDATA.
Assumes that the file was correctly created during setup.
Definition at line 26 of file settings_db.py.
def get_user_db_path() -> str:
    """
    @brief Returns the absolute path to the user_config.db file in LOCALAPPDATA.
    Assumes that the file was correctly created during setup.
    """
    return USER_DB_PATH
Referenced by add_recent_file(), get_recent_files(), get_setting(), init_db(), and set_setting().
init_db()
settings_db.init_db ()
@brief Initializes the SQLite database if not already present.
Creates `settings` and `recent_files` tables if they do not exist.
Does not insert any default values.
Definition at line 35 of file settings_db.py.
def init_db():
    """
    @brief Initializes the SQLite database if not already present.
    Creates `settings` and `recent_files` tables if they do not exist.
    Does not insert any default values.
    """
    conn = sqlite3.connect(get_user_db_path())
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS recent_files (
            path TEXT PRIMARY KEY,
            filename TEXT NOT NULL,
            last_opened TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.commit()
    conn.close()
References get_user_db_path().
set_setting()
settings_db.set_setting (str key, str value)
@brief Sets or updates a configuration key-value pair in the settings table.
@param key The name of the setting (e.g. "language").
@param value The string value to store.
Definition at line 61 of file settings_db.py.
def set_setting(key: str, value: str):
    """
    @brief Sets or updates a configuration key-value pair in the settings table.
    @param key The name of the setting (e.g. "language").
    @param value The string value to store.
    """
    if key == "language":
        logger = GeneralLogHandler()
        logger.debug(f"set_setting('language', '{value}') chiamato da:\n{''.join(traceback.format_stack(limit=5))}")
    conn = sqlite3.connect(get_user_db_path())
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO settings (key, value) VALUES (?, ?)
        ON CONFLICT(key) DO UPDATE SET value=excluded.value
    """, (key, value))
    conn.commit()
    conn.close()
References get_user_db_path().
Variable Documentation
logger
settings_db.logger = GeneralLogHandler()
Definition at line 24 of file settings_db.py.