esphome:
  name: {{ name }}
  friendly_name: {{ friendly_name }}

esp32:
  board: {{ board }}
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: "{{ ssid }}"
  password: "{{ password }}"

captive_portal:
