APP_NAME = "ESPHomeGuiEasy"
SW_ICON_PATH = "assets/icon/esphomeguieasy_icon.png"

MAIN_WINDOW_HEIGHT = 900
MAIN_WINDOW_WIDTH = 1500

MAIN_SPLITTER_LEFT_COLUMN = 750
MAIN_SPLITTER_RIGHT_COLUMN = 750 

